name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-build.yaml@main
    needs: semver
    with:
      imageName: secrets-distributor
      tag: ${{ needs.semver.outputs.GitVersion_SemVer }}
    secrets: inherit

  submodule:
    uses: lsc-sde/lsc-sde/.github/workflows/update-submodules.yaml@main
    needs: 
    - semver
    - buildandpush
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      directory: docker/secrets-distributor
    secrets: inherit
